name: Comment on New Issue
run-name: "New Issue #${{ github.event.issue.number }} Created By ${{ github.event.issue.user.login }}"

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Hi ${context.payload.issue.user.login},\n\n👋 Thanks for reporting!`
            })
