name: Reusable Comment on Issue

on:
  workflow_call:
    inputs:
      owner:
        required: true
        type: string
      repo:
        required: true
        type: string
      issue_number:
        required: true
        type: string
      user_login:
        required: true
        type: string
      body:
        required: false
        type: string

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            const body = "${{ github.event.inputs.body }}" || `Hi @${{ github.event.inputs.user_login }},\n\n👋 Thanks for opening this issue!`;
            github.rest.issues.createComment({
              issue_number: "${{ github.event.inputs.issue_number }}",
              owner: "${{ github.event.inputs.owner }}",
              repo: "${{ github.event.inputs.repo }}",
              body: body
            })
